version: '3.1'
services:

  mongo:
    image: mongo:4.0.4
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
    networks:
      - backend
    secrets:
      - secret_password
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/secret_password

  express:
    image: mongo-express:0.49
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 60s
    ports:
      - 8081:8081
    networks:
      - backend
    depends_on:
      - mongo
    secrets:
      - secret_password
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

networks:
  backend:
volumes:
  db-data:
secrets:
  secret_password:
    file: ./secret_password.txt