version: "3.1"
services:
  node:
    image: node:11
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - 4000:4000
    command: "npm start"